# Generated by Django 4.0.3 on 2022-03-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_professor_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
