# Generated by Django 4.0.3 on 2022-03-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='n_votes',
            field=models.IntegerField(default=0),
        ),
    ]
